### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by bafplus**
Dutch translation for Snappy.

Maybe an idea to make a language selector in the settings screen so users can select there own language?

### CODE REVIEW

**Comment by bafplus** [comment]
Added dutch language to android and added server files and reorganized

**Comment by jaullo** [comment]
Hello @bafplus, i will merge this in my project soon

**Comment by bafplus** [comment]
Thanks, as soon as my server is fully functional i will also provode dutch language files for the server.

Van: jaullo [mailto:notifications@github.com] 
Verzonden: woensdag 4 maart 2015 20:08
Aan: jaullo/Snappy
CC: bafplus
Onderwerp: Re: [Snappy] Added Dutch translation (#5)

Hello @bafplus https://github.com/bafplus , i will merge this in my project soon

**Comment by jaullo** [comment]
Great, let me know when u have the backend in Dutch. Maybe we could made an interchange. I could provide u with a backend in spanish. 

:)

**Pull request merged**
